# Generated by Django 5.2.17 on 2026-08-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadministrador'), ('SECRETARIA', 'Secretaria Municipal'), ('TECNICO', 'Técnico Pedagógico'), ('GESTOR', 'Gestor Escolar'), ('COORDENADOR', 'Coordenador Pedagógico'), ('PROFESSOR', 'Professor'), ('AEE', 'Atendimento Educacional Especializado')], max_length=32, unique=True),
        ),
    ]
