# Generated by Django 5.2.17 on 2026-08-08 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('VISUAL', 'Visual'), ('AUDITORY', 'Auditiva'), ('MOTOR', 'Motora'), ('COGNITIVE', 'Cognitiva / atenção'), ('SENSORY', 'Sensorial'), ('COMMUNICATION', 'Comunicação')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Accessibility categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessibilityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('css_class', models.CharField(blank=True, help_text='Classe CSS opcional aplicada no player (ex.: a11y-large-text).', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features', to='accessibility.accessibilitycategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'name'],
                'permissions': [('view_student_accessibility', 'Pode ver recursos de acessibilidade do estudante'), ('change_student_accessibility', 'Pode alterar perfil de acessibilidade do estudante'), ('manage_support_plan', 'Pode gerenciar plano de apoio pedagógico')],
            },
        ),
        migrations.CreateModel(
            name='StudentAccessibilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Observações pedagógicas sobre acesso e apoio. Não incluir CID, laudos ou dados clínicos.')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_profile', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_accessibility_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de acessibilidade do estudante',
                'verbose_name_plural': 'Perfis de acessibilidade',
            },
        ),
        migrations.CreateModel(
            name='StudentSupportPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('review', 'Em revisão'), ('completed', 'Concluído'), ('archived', 'Arquivado')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas pedagógicas do plano de apoio. Sem conteúdo clínico.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_plans', to=settings.AUTH_USER_MODEL)),
                ('responsible_users', models.ManyToManyField(blank=True, related_name='support_plans', to=settings.AUTH_USER_MODEL)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_plans', to='schools.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_plans', to='students.student')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSupportStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accessibility_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_strategies', to='accessibility.accessibilityfeature')),
                ('support_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='accessibility.studentsupportplan')),
            ],
            options={
                'verbose_name_plural': 'Student support strategies',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StudentAccessibilityFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_links', to='accessibility.accessibilityfeature')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_links', to='accessibility.studentaccessibilityprofile')),
            ],
            options={
                'ordering': ['priority', 'feature__name'],
                'unique_together': {('profile', 'feature')},
            },
        ),
    ]
