# Generated by Django 5.2.17 on 2026-08-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_label', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PedagogicalMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Pedagogical matrices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('matrix_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='curriculum.matrixversion')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('matrix_version', 'code')},
            },
        ),
        migrations.AddField(
            model_name='matrixversion',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='curriculum.pedagogicalmatrix'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='curriculum.developmentdimension')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('dimension', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='matrixversion',
            unique_together={('matrix', 'version_label')},
        ),
        migrations.CreateModel(
            name='SkillProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('from_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_links', to='curriculum.skill')),
                ('to_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_links', to='curriculum.skill')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('from_skill', 'to_skill')},
            },
        ),
        migrations.CreateModel(
            name='StatusLabelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('severity', models.PositiveSmallIntegerField(default=0, help_text='0=não observado, maior = mais atenção necessária ou progresso')),
                ('color_token', models.CharField(blank=True, max_length=30)),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('matrix_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_labels', to='curriculum.matrixversion')),
            ],
            options={
                'ordering': ['order', 'code'],
                'unique_together': {('matrix_version', 'code')},
            },
        ),
    ]
