# Generated by Django 5.2.17 on 2026-08-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentdimension',
            name='practice_axis',
            field=models.CharField(blank=True, help_text='Eixo/prática de linguagem do Currículo PE (ex.: Oralidade, Análise linguística)', max_length=100),
        ),
        migrations.AddField(
            model_name='matrixversion',
            name='framework_reference',
            field=models.CharField(blank=True, default='', help_text='Ex.: Currículo de Pernambuco / BNCC — Língua Portuguesa Anos Iniciais', max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='bncc_code',
            field=models.CharField(blank=True, help_text='Código Currículo PE / BNCC (ex.: EF01LP06PE)', max_length=40),
        ),
        migrations.AddField(
            model_name='skill',
            name='curriculum_notes',
            field=models.TextField(blank=True, help_text='Orientação pedagógica alinhada ao Currículo de Pernambuco'),
        ),
        migrations.AddField(
            model_name='skill',
            name='knowledge_object',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
