# Generated by Django 5.2.17 on 2026-08-09 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventiontemplate',
            name='suggested_activity_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Duração sugerida da atividade em uma aula (minutos).'),
        ),
        migrations.AddField(
            model_name='studentintervention',
            name='classroom_intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_links', to='interventions.classroomintervention'),
        ),
        migrations.AddField(
            model_name='studentintervention',
            name='followup_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentintervention',
            name='followup_result',
            field=models.CharField(blank=True, choices=[('progressed', 'Avançou'), ('needs_more_support', 'Ainda precisa de apoio'), ('not_observed', 'Não participou / não foi possível observar')], max_length=32),
        ),
    ]
