# Generated by Django 5.2.17 on 2026-08-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão lógica'), ('import', 'Importação'), ('permission', 'Permissão'), ('enrollment', 'Matrícula'), ('instrument', 'Instrumento'), ('login', 'Login'), ('accessibility', 'Acessibilidade'), ('support_plan', 'Plano de apoio')], max_length=32),
        ),
    ]
