# Generated by Django 5.2.17 on 2026-08-08 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('interventions', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instrument_type', models.CharField(choices=[('digital', 'Digital / Gamificada'), ('observational', 'Observacional')], max_length=20)),
                ('estimated_minutes', models.PositiveIntegerField(default=10)),
                ('is_published', models.BooleanField(default=True)),
                ('matrix_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='curriculum.matrixversion')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='curriculum.skill')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('item_type', models.CharField(choices=[('image_select', 'Imagem → selecionar imagem'), ('audio_image', 'Áudio/texto → selecionar imagem'), ('image_choice', 'Imagem → selecionar alternativa'), ('single_select', 'Seleção simples'), ('visual_tf', 'Verdadeiro/Falso visual'), ('observation_scale', 'Escala observacional')], max_length=30)),
                ('prompt', models.TextField()),
                ('prompt_audio', models.FileField(blank=True, null=True, upload_to='assessments/audio/')),
                ('prompt_image', models.ImageField(blank=True, null=True, upload_to='assessments/images/')),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.assessmentinstrument')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assessments/options/')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score_value', models.IntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.assessmentitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('abandoned', 'Abandonada')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_item_order', models.PositiveIntegerField(default=0)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_sessions', to='students.enrollment')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='assessments.assessmentinstrument')),
                ('matrix_version', models.ForeignKey(help_text='Versão congelada no início da sessão', on_delete=django.db.models.deletion.PROTECT, related_name='assessment_sessions', to='curriculum.matrixversion')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('result_code', models.CharField(max_length=50)),
                ('status_code', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='assessments.assessmentinstrument')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='curriculum.skill')),
            ],
            options={
                'ordering': ['min_score'],
            },
        ),
        migrations.CreateModel(
            name='SkillResultMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needs_attention', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('intervention_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_mappings', to='interventions.interventiontemplate')),
                ('scoring_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='assessments.scoringrule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_value', models.TextField(blank=True)),
                ('score_value', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.assessmentitem')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.assessmentoption')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessmentsession')),
            ],
            options={
                'ordering': ['item__order'],
                'unique_together': {('session', 'item')},
            },
        ),
        migrations.CreateModel(
            name='SessionSkillResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('result_code', models.CharField(blank=True, max_length=50)),
                ('status_code', models.CharField(max_length=50)),
                ('status_label', models.CharField(max_length=100)),
                ('needs_attention', models.BooleanField(default=False)),
                ('recommended_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interventions.interventiontemplate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_results', to='assessments.assessmentsession')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_results', to='curriculum.skill')),
            ],
            options={
                'unique_together': {('session', 'skill')},
            },
        ),
    ]
