# Generated by Django 5.2.17 on 2026-08-08 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessibility', '0001_accessibility_inclusive_phase'),
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentinstrument',
            name='time_is_construct',
            field=models.BooleanField(default=False, help_text='Se verdadeiro, tempo faz parte da habilidade avaliada. Caso contrário, tempo é só metadado.'),
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='code',
            field=models.CharField(blank=True, help_text='Código estável para biblioteca (ex.: RIM-001)', max_length=40),
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='prompt_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assessmentoption',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='active_features_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='counts_toward_score',
            field=models.BooleanField(default=True, help_text='False para NOT_APPLICABLE / BLOCKED — barreira ≠ baixo desempenho.'),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='equivalence_applied',
            field=models.CharField(choices=[('STANDARD', 'Padrão'), ('EQUIVALENT', 'Equivalente'), ('ALTERNATIVE', 'Alternativo'), ('NOT_APPLICABLE', 'Não aplicável'), ('BLOCKED', 'Bloqueado por acessibilidade'), ('REQUIRES_ALTERNATIVE', 'Requer instrumento alternativo'), ('REQUIRES_PEDAGOGICAL_REVIEW', 'Requer revisão pedagógica')], default='STANDARD', max_length=40),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='instruction_repeats',
            field=models.PositiveIntegerField(default=0, help_text='Repetições de instrução; não reduz pontuação automaticamente.'),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='is_observational',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='original_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='original_responses', to='assessments.assessmentitem'),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='response_time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='variant_name_snapshot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='variant_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='active_features',
            field=models.JSONField(blank=True, default=list, help_text='Códigos de recursos de acessibilidade ativos na sessão (snapshot).'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='adaptation_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Resumo imutável da montagem adaptativa (contagens e decisões).'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='application_mode',
            field=models.CharField(choices=[('standard', 'Padrão'), ('adapted', 'Adaptada'), ('observational', 'Observacional')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Metadado de tempo; não reduz pontuação automaticamente.', null=True),
        ),
        migrations.AddField(
            model_name='sessionskillresult',
            name='accessibility_note',
            field=models.CharField(blank=True, help_text='Ex.: versão acessível utilizada; não implica redução de expectativa.', max_length=255),
        ),
        migrations.AlterField(
            model_name='assessmentitem',
            name='item_type',
            field=models.CharField(choices=[('image_select', 'Imagem → selecionar imagem'), ('audio_image', 'Áudio/texto → selecionar imagem'), ('image_choice', 'Imagem → selecionar alternativa'), ('single_select', 'Seleção simples'), ('visual_tf', 'Verdadeiro/Falso visual'), ('observation_scale', 'Escala observacional'), ('select_then_match', 'Selecionar e associar (sem arrastar)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('partially_completed', 'Parcialmente concluída'), ('not_applicable', 'Não aplicável'), ('requires_alternative_instrument', 'Requer instrumento alternativo'), ('accessibility_blocked', 'Bloqueada por acessibilidade'), ('abandoned', 'Abandonada')], default='in_progress', max_length=40),
        ),
        migrations.CreateModel(
            name='AssessmentItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('instruction_text', models.TextField(blank=True)),
                ('instruction_audio', models.FileField(blank=True, null=True, upload_to='assessments/variants/audio/')),
                ('instruction_image', models.ImageField(blank=True, null=True, upload_to='assessments/variants/images/')),
                ('instruction_image_alt', models.CharField(blank=True, max_length=255)),
                ('instruction_video', models.FileField(blank=True, null=True, upload_to='assessments/variants/video/')),
                ('instruction_libras_video', models.FileField(blank=True, null=True, upload_to='assessments/variants/libras/')),
                ('item_type_override', models.CharField(blank=True, choices=[('image_select', 'Imagem → selecionar imagem'), ('audio_image', 'Áudio/texto → selecionar imagem'), ('image_choice', 'Imagem → selecionar alternativa'), ('single_select', 'Seleção simples'), ('visual_tf', 'Verdadeiro/Falso visual'), ('observation_scale', 'Escala observacional'), ('select_then_match', 'Selecionar e associar (sem arrastar)')], help_text='Se preenchido, altera o modo de interação sem mudar o item canônico.', max_length=30)),
                ('equivalence_status', models.CharField(choices=[('EQUIVALENT', 'Equivalente (acomodação de acesso)'), ('ALTERNATIVE', 'Alternativo (revisão pedagógica)'), ('NOT_EQUIVALENT', 'Não equivalente')], max_length=20)),
                ('equivalence_notes', models.TextField(blank=True)),
                ('adaptation_type', models.CharField(choices=[('ACCESS_ACCOMMODATION', 'Acomodação de acesso'), ('PEDAGOGICAL_MODIFICATION', 'Modificação pedagógica')], default='ACCESS_ACCOMMODATION', max_length=40)),
                ('pedagogical_approval_status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Enviado'), ('PEDAGOGICAL_REVIEW', 'Revisão pedagógica'), ('APPROVED', 'Aprovado'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=30)),
                ('justification', models.TextField(blank=True, help_text='Obrigatório para modificação pedagógica.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_item_variants', to=settings.AUTH_USER_MODEL)),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='assessments.assessmentitem')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_item_variants', to=settings.AUTH_USER_MODEL)),
                ('support_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_variants', to='accessibility.studentsupportplan')),
                ('supported_features', models.ManyToManyField(blank=True, related_name='supported_variants', to='accessibility.accessibilityfeature')),
            ],
            options={
                'ordering': ['parent_item_id', 'name', 'version'],
                'unique_together': {('parent_item', 'name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='variant_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.assessmentitemvariant'),
        ),
        migrations.CreateModel(
            name='ItemAccessRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('requires_vision', 'Requer visão'), ('requires_audio', 'Requer áudio'), ('requires_motor_precision', 'Requer precisão motora'), ('requires_drag', 'Requer arrastar e soltar'), ('requires_reading', 'Requer leitura'), ('requires_color_discrimination', 'Requer discriminação de cores'), ('requires_timed_response', 'Requer resposta cronometrada'), ('supports_screen_reader', 'Compatível com leitor de tela'), ('supports_keyboard', 'Compatível com teclado')], max_length=64)),
                ('is_required', models.BooleanField(default=True, help_text='False = capability/support flag (supports_*); True = hard requirement.')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requirements', to='assessments.assessmentitem')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('item', 'code')},
            },
        ),
        migrations.CreateModel(
            name='VariantAccessRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('requires_vision', 'Requer visão'), ('requires_audio', 'Requer áudio'), ('requires_motor_precision', 'Requer precisão motora'), ('requires_drag', 'Requer arrastar e soltar'), ('requires_reading', 'Requer leitura'), ('requires_color_discrimination', 'Requer discriminação de cores'), ('requires_timed_response', 'Requer resposta cronometrada'), ('supports_screen_reader', 'Compatível com leitor de tela'), ('supports_keyboard', 'Compatível com teclado')], max_length=64)),
                ('is_required', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requirements', to='assessments.assessmentitemvariant')),
            ],
            options={
                'unique_together': {('variant', 'code')},
            },
        ),
    ]
