# Generated by Django 5.2.17 on 2026-08-08 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidences/%Y/%m/')),
                ('file_type', models.CharField(choices=[('photo', 'Foto'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('text', 'Observação textual'), ('none', 'Sem arquivo')], default='none', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='students.enrollment')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='curriculum.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Evidences',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
