# Generated by Django 5.2.17 on 2026-08-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planactivity',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Atividade do plano', 'verbose_name_plural': 'Atividades do plano'},
        ),
        migrations.AddField(
            model_name='pedagogicalplan',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedagogicalplan',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('suggested', 'Sugestão aceita'), ('adjusted', 'Sugestão ajustada')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='planactivity',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
