# Generated by Django 5.2.17 on 2026-08-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('network', 'Rede'), ('school', 'Escola'), ('classroom', 'Turma'), ('student', 'Estudante')], max_length=20)),
                ('metric_key', models.CharField(max_length=100)),
                ('metric_value', models.FloatField(default=0)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='schools.classroom')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='schools.municipality')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='schools.school')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='schools.schoolyear')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='curriculum.skill')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['scope', 'metric_key'], name='analytics_a_scope_f6ff9d_idx'), models.Index(fields=['school_year', 'scope'], name='analytics_a_school__74acd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentSkillStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_code', models.CharField(max_length=50)),
                ('status_label', models.CharField(max_length=100)),
                ('needs_attention', models.BooleanField(default=False)),
                ('raw_score', models.IntegerField(blank=True, null=True)),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_statuses', to='students.enrollment')),
                ('last_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_statuses', to='assessments.assessmentsession')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_statuses', to='curriculum.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_statuses', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Student skill statuses',
                'ordering': ['skill__name'],
                'unique_together': {('student', 'skill')},
            },
        ),
    ]
